import type { Metadata } from "next";
import "./globals.css";

import { Navbar } from "@/components/core/Navbar";
import { Footer } from "@/components/core/Footer";


export const metadata: Metadata = {
  title: "Kormi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>

        <Navbar/>

        <main className="sm:mx-4 sm:px-4
          lg:mx-8 lg:px-8"
        >
          {children}
        </main>

        <Footer/>

      </body>

    </html>
  );
}
